/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "4fce3adc3e249320ec0298369d7b3b40f0235f6a"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
