/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "98e8e393fbc845f4490be638376fec8a67f705fa"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
