/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "94fa7922d0fadb1897df9cb6c278f79ab6f1f0c0"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
